# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'trivia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for trivia
  pod 'HTMLString', '~> 4.0'

  target 'triviaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'triviaUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
